[package]
name = "mod_hello_world"
version = "0.1.0"
authors = ["studersi <mail@studer.si>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.mod_rs]
path = "../.."
